### ISSUE TITLE
TypeError: <lambda>() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by mubeenmeo344** [vnbot2/object-locator#3]
Traceback (most recent call last):
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev\pydevd.py", line 2066, in <module>
    main()
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev\pydevd.py", line 2060, in main
    globals = debugger.run(setup['file'], None, None, is_module)
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev\pydevd.py", line 1411, in run
    return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev\pydevd.py", line 1418, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "C:/Users/Mubeen/OneDrive/Desktop/object-locator-master/train.py", line 81, in <module>
    term1, term2, term_3 = loss_loc(prob_map, locs)
  File "C:\Users\Mubeen\OneDrive\Desktop\object-locator-master\losses.py", line 98, in __call__
    i, term_1, term_2, term_3 = tf.while_loop(cond, body, [i, term_1_init, term_2_init, term_3_init])
  File "C:\Users\Mubeen\OneDrive\Desktop\object-locator-master\venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3556, in while_loop
    return_same_structure)
  File "C:\Users\Mubeen\OneDrive\Desktop\object-locator-master\venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3087, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "C:\Users\Mubeen\OneDrive\Desktop\object-locator-master\venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3007, in _BuildLoop
    c = ops.convert_to_tensor(pred(*packed_vars))
TypeError: <lambda>() takes 3 positional arguments but 4 were given

**Comment by mubeenmeo344** [comment]
> Traceback (most recent call last):
> File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev\pydevd.py", line 2066, in
> main()
> File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev\pydevd.py", line 2060, in main
> globals = debugger.run(setup['file'], None, None, is_module)
> File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev\pydevd.py", line 1411, in run
> return self._exec(is_module, entry_point_fn, module_name, file, globals, locals)
> File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev\pydevd.py", line 1418, in _exec
> pydev_imports.execfile(file, globals, locals) # execute the script
> File "C:\Program Files\JetBrains\PyCharm Community Edition with Anaconda plugin 2019.2.2\helpers\pydev_pydev_imps_pydev_execfile.py", line 18, in execfile
> exec(compile(contents+"\n", file, 'exec'), glob, loc)
> File "C:/Users/Mubeen/OneDrive/Desktop/object-locator-master/train.py", line 81, in
> term1, term2, term_3 = loss_loc(prob_map, locs)
> File "C:\Users\Mubeen\OneDrive\Desktop\object-locator-master\losses.py", line 98, in **call**
> i, term_1, term_2, term_3 = tf.while_loop(cond, body, [i, term_1_init, term_2_init, term_3_init])
> File "C:\Users\Mubeen\OneDrive\Desktop\object-locator-master\venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3556, in while_loop
> return_same_structure)
> File "C:\Users\Mubeen\OneDrive\Desktop\object-locator-master\venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3087, in BuildLoop
> pred, body, original_loop_vars, loop_vars, shape_invariants)
> File "C:\Users\Mubeen\OneDrive\Desktop\object-locator-master\venv\lib\site-packages\tensorflow\python\ops\control_flow_ops.py", line 3007, in _BuildLoop
> c = ops.convert_to_tensor(pred(*packed_vars))
> TypeError: () takes 3 positional arguments but 4 were given

Kindly tell me.....whats wrond with this code.......I just try to run yourgiven repository

**Comment by ananyashivam** [comment]
have u been able to resolve the problem?
